In [1]:
import pandas as pd
import numpy as np

In [2]:
fnlttSingAcntAll_df = pd.read_csv('./fin_data/fnlttSinglAcntAll_2022_raw_data.csv')
fnlttSingAcntAll_df.head()

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,...,frmtrm_nm,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_amount,ord,currency,thstrm_add_amount,frmtrm_q_nm,frmtrm_q_amount,frmtrm_add_amount
0,20230316000799,11011,2022,173944,BS,재무상태표,ifrs-full_CurrentAssets,유동자산,-,제 43 기,...,제 42 기,6.865631e+10,제 41 기,4.230933e+10,1,KRW,NaN,NaN,NaN,NaN
1,20230316000799,11011,2022,173944,BS,재무상태표,ifrs-full_CashAndCashEquivalents,현금및현금성자산,-,제 43 기,...,제 42 기,3.435252e+10,제 41 기,8.231505e+09,2,KRW,NaN,NaN,NaN,NaN
2,20230316000799,11011,2022,173944,BS,재무상태표,dart_ShortTermTradeReceivable,매출채권,-,제 43 기,...,제 42 기,1.200390e+10,제 41 기,8.236231e+09,3,KRW,NaN,NaN,NaN,NaN
3,20230316000799,11011,2022,173944,BS,재무상태표,dart_CurrentDerivativeAsset,계약자산,-,제 43 기,...,제 42 기,1.545574e+09,제 41 기,3.390680e+09,4,KRW,NaN,NaN,NaN,NaN
4,20230316000799,11011,2022,173944,BS,재무상태표,ifrs-full_OtherCurrentFinancialAssets,기타유동금융자산,-,제 43 기,...,제 42 기,3.420561e+08,제 41 기,9.252237e+08,5,KRW,NaN,NaN,NaN,NaN

In [5]:
fnlttSingAcntAll_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390078 entries, 0 to 390077
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   rcept_no           390078 non-null  int64
 1   reprt_code         390078 non-null  int64
 2   bsns_year          390078 non-null  int64
 3   corp_code          390078 non-null  int64
 4   sj_div             390078 non-null  object
 5   sj_nm              390078 non-null  object
 6   account_id         390078 non-null  object
 7   account_nm         390078 non-null  object
 8   account_detail     390078 non-null  object
 9   thstrm_nm          390078 non-null  object
 10  thstrm_amount      370423 non-null  float64
 11  frmtrm_nm          195293 non-null  object
 12  frmtrm_amount      183181 non-null  float64
 13  bfefrmtrm_nm       108042 non-null  object
 14  bfefrmtrm_amount   97130 non-null   float64
 15  ord                390078 non-null  int64
 16  currency           390078 non-null  object
 17  thstrm_add_amount  45101 non-null   float64
 18  frmtrm_q_nm        194213 non-null  object
 19  frmtrm_q_amount    184218 non-null  float64
 20  frmtrm_add_amount  45043 non-null   float64
dtypes: float64(6), int64(5), object(10)
memory usage: 62.5+ MB

In [54]:
# fnlttSingAcntAll_df['sj_nm'].unique()
# array(['재무상태표', '포괄손익계산서', '현금흐름표', '자본변동표', '손익계산서'], dtype=object)
sj_nm = '재무상태표'
def sj_nm_list_account_nm(sj_nm):
    reprt_code=11011
    str_expr = "(sj_nm == @sj_nm) and (reprt_code==@reprt_code)"
    list_acc = fnlttSingAcntAll_df.query(str_expr)['account_nm'].unique().tolist()
    print(sj_nm,'의 회계계정명 : ',len(list_acc))
    print()
    for name in list_acc:
        print(name, end=', ')
# fnlttSingAcntAll_df[(fnlttSingAcntAll_df.sj_nm=='현금흐름표') & (fnlttSingAcntAll_df.reprt_code==11011)]['account_nm'].unique().__len__()

In [ ]:
sj_nm_list = ['재무상태표', '포괄손익계산서', '현금흐름표', '자본변동표', '손익계산서']
for sj_nm in sj_nm_list:
    sj_nm_list_account_nm(sj_nm)

In [15]:
account_nm_uniq = fnlttSingAcntAll_df.loc[fnlttSingAcntAll_df['reprt_code']==11011]['account_nm'].unique()
display(account_nm_uniq.tolist()[-10:])

['비유동생물자산의 처분',
 '기타포괄금융자산의 취득',
 '기타포괄금융자산의 처분',
 '파생상품계약에 따른 현금유출',
 '순확정급여의 재측정 요소',
 '순확정부채의 재측정손익',
 '위험회피수단으로 지정된 파생상품평가손익',
 '단기기타금융자산의 처분',
 '단기기타금융자산의 취득',
 '순확정부채의 재측정요소']

In [20]:
fnlttSingAcntAll_df[fnlttSingAcntAll_df['account_nm'].isin(['유동부채','단기차입금','장기차입금'])]

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,...,frmtrm_nm,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_amount,ord,currency,thstrm_add_amount,frmtrm_q_nm,frmtrm_q_amount,frmtrm_add_amount
19,20200330003191,11011,2019,159412,BS,재무상태표,ifrs-full_CurrentLiabilities,유동부채,-,제 64 기,...,제 63 기,1.925478e+11,제 62 기,1.631603e+11,21,KRW,NaN,NaN,NaN,NaN
134,20191114001695,11014,2019,159412,BS,재무상태표,ifrs-full_CurrentLiabilities,유동부채,-,제 64 기 3분기말,...,제 63 기말,1.925478e+11,NaN,NaN,20,KRW,NaN,NaN,NaN,NaN
238,20190814001494,11012,2019,159412,BS,재무상태표,ifrs_CurrentLiabilities,유동부채,-,제 64 기 반기말,...,제 63 기말,1.925478e+11,NaN,NaN,20,KRW,NaN,NaN,NaN,NaN
343,20190515001740,11013,2019,159412,BS,재무상태표,ifrs_CurrentLiabilities,유동부채,-,제 64 기 1분기말,...,제 63 기말,1.925478e+11,NaN,NaN,21,KRW,NaN,NaN,NaN,NaN
438,20200330002594,11011,2019,173944,BS,재무상태표,ifrs-full_CurrentLiabilities,유동부채,-,제 40 기,...,제 39 기,3.113016e+10,제 38 기,2.067026e+10,19,KRW,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389893,20190814000663,11012,2019,422895,BS,재무상태표,ifrs_ShorttermBorrowings,단기차입금,-,제 18 기 반기말,...,제 17 기말,4.062040e+10,NaN,NaN,20,KRW,NaN,NaN,NaN,NaN
389898,20190814000663,11012,2019,422895,BS,재무상태표,dart_LongTermBorrowingsGross,장기차입금,-,제 18 기 반기말,...,제 17 기말,3.673750e+09,NaN,NaN,25,KRW,NaN,NaN,NaN,NaN
389994,20190515000886,11013,2019,422895,BS,재무상태표,ifrs_CurrentLiabilities,유동부채,-,제 18 기 1분기말,...,제 17 기말,8.751708e+10,NaN,NaN,17,KRW,NaN,NaN,NaN,NaN
389997,20190515000886,11013,2019,422895,BS,재무상태표,ifrs_ShorttermBorrowings,단기차입금,-,제 18 기 1분기말,...,제 17 기말,4.062040e+10,NaN,NaN,20,KRW,NaN,NaN,NaN,NaN
390002,20190515000886,11013,2019,422895,BS,재무상태표,dart_LongTermBorrowingsGross,장기차입금,-,제 18 기 1분기말,...,제 17 기말,3.673750e+09,NaN,NaN,25,KRW,NaN,NaN,NaN,NaN

In [18]:
fnlttSingAcntAll_df['account_detail'][-10:]

390068        자본 [member]|이익잉여금 [member]
390069                   별도재무제표 [member]
390070                   별도재무제표 [member]
390071    자본 [member]|기타포괄손익누계액 [member]
390072        자본 [member]|자본잉여금 [member]
390073          자본 [member]|자본금 [member]
390074        자본 [member]|이익잉여금 [member]
390075                  자본 [member]|기타자본
390076                   별도재무제표 [member]
390077    자본 [member]|기타포괄손익누계액 [member]
Name: account_detail, dtype: object